# Generated by Django 6.0.6 on 2026-06-25 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("election", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="states",
            name="description",
            field=models.TextField(blank=True, default="", null=True),
        ),
    ]
