# Generated by Django 6.0.6 on 2026-06-26 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("election", "0002_states_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="constituency",
            name="description",
            field=models.TextField(blank=True, default="", null=True),
        ),
    ]
