# Generated by Django 6.0.6 on 2026-06-26 06:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("election", "0003_alter_constituency_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="constituency",
            name="state",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="constituencies",
                to="election.states",
            ),
        ),
    ]
