# Generated by Django 6.0.6 on 2026-06-26 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("election", "0005_symbol_candidate_voters_vote"),
    ]

    operations = [
        migrations.AddField(
            model_name="vote",
            name="casted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
