# Generated by Django 6.0.6 on 2026-06-29 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("election", "0006_vote_casted_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="voters",
            name="aadhaar",
            field=models.CharField(db_index=True, default="adhaar1234", max_length=100),
            preserve_default=False,
        ),
    ]
